sudo: required

branches:  
  only:
    - master

language: node_js

services:
  - docker

node_js:
  - stable

before_install: 
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_success:
  - npm run release
  - docker build -t remojansen/redux-bootstrap-example .
  - docker push remojansen/redux-bootstrap-example
